function [CT header]=GetHeadofGeDataSet(FN)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%18 floating point header, followed by 888x64 float projections (the number of projection views is specified by the total-view parameter.
%      The header information is below: (Begin with 0)
%                 Hdr(2):  source-to-detector distance (mm)
%                 Hdr(3):  source-to-iso distance (mm)
%                 Hdr(4):  detector cell pitch (at detector surface) (mm)
%                 Hdr(5):  first projection view angle (degree)
%                 Hdr(8):  number of views per rotation
%                 Hdr(9):  total number of views
%                 Hdr(10): number of detector channels per row
%                 Hdr(11): iso-channel location
%                 Hdr(12): number of detector rows
%                 Hdr(14): helical pitch

fid    = fopen(FN);
header = fread(fid,18,'single');
%data = fread(fid,[Width, Heigh],'single');
fclose (fid);  
CT = struct('Source2DetDis', [header(3)],...
            'Source2IsoDis', [header(4)],...
            'DetCellPitch',  [header(5)],...
            'BeginViewAngle',[header(6)],...
            'NumberOfViewPerRotation',[header(9)],...
            'TotalViewNumber',[header(10)],...
            'NumberOfDetChannelPerRow',[header(11)],...
            'NumberOfDetectorRow',[header(13)],...
            'IsoChannelLocation',[header(12)],...
            'SliceHeigh',[header(14)],...
            'HelicalPitch',[header(15)]);
